### ISSUE TITLE
Switching tracks no longer works

### ISSUE THREAD

**Issue by kraM1tt** [jellyfin/jellyfin-tizen#323] opened 2024-12-19 15:57 UTC
Ever since having to reinstall due to Tizen 8.0 update, switching audio/subtitle tracks does nothing. It will tick the new track and select it, but it'll never actually change. Only way to make it work is modify the .mkv header info and disable tracks you don't want.

10.10.3 and latest client via master too.

Works fine on AndroidTV or Android/Findroid phone apps

**Comment by dmitrylyzo** [comment] 2024-12-19 17:05
Duplicate of #293
https://github.com/jellyfin/jellyfin-tizen/issues/293#issuecomment-2473476368

**Closed** 2024-12-19 17:06 UTC
Labels: duplicate
