### ISSUE TITLE
Compiling on windows?

### ISSUE THREAD

**Issue by Dokman** [jellyfin/jellyfin-tizen#2] opened 2020-01-23 01:50 UTC
is possible? because it tells me that some library are not working

**Comment by dmitrylyzo** [comment] 2020-01-23 07:25
This works for me.

**Prerequisites**
* jdk-8
* Tizen Studio 3.6 with CLI (command line interface)
* Node.js
* Yarn

> All tools (yarn, node, tizen) are assumed to be added to the `PATH` environment variable.

**Build Jellyfin Web** - same
```sh
cd jellyfin-web
yarn install
```

At **Prepare Interface** stage
```sh
cd jellyfin-tizen
set JELLYFIN_WEB_DIR=c:\jellyfin\jellyfin-web\dist
npm install
npx gulp
```

> It is better that `JELLYFIN_WEB_DIR` be absolute

At **Build WGT** stage
```sh
tizen.bat build-web -e ".*" -e gulpfile.js -e README.md -e "node_modules/*" -e "package*.json" -e "yarn.lock"
tizen.bat package -t wgt -o . -- .buildResult
```

**Comment by Dokman** [comment] 2020-01-23 18:15
Thanks

**Comment by Dokman** [comment] 2020-01-23 23:19
Another question how i install my wgt to my tizen tv?

**Comment by Dokman** [comment] 2020-01-23 23:28
![image](https://user-images.githubusercontent.com/2290904/73032833-79c4ef80-3e40-11ea-9f5d-1f9aa6505348.png)

**Comment by dmitrylyzo** [comment] 2020-01-24 07:27
@Dokman A line `Using jellyfin-web from C:\jellyfin\jellyfin-tizen\node_modules\jellyfin-web\dist` indicates that environment variable `JELLYFIN_WEB_DIR` is not set before `npm install`.
_It turned out that `npx gulp` is not needed after `npm install` - it runs automatically._

I can make `jellyfin-web` module to be fetched automatically - this simplifies the build process, but it will be redundant if you need to bundle with other version of `jellyfin-web` (pointed by `JELLYFIN_WEB_DIR`). I just looked at how this is done in `jellyfin-android`.

> Another question how i install my wgt to my tizen tv?

https://github.com/dmitrylyzo/jellyfin-tizen#deploy-to-tv
In Windows, `sdb` is located at `<TIZEN_STUDIO_INSTALL_DIR>\tools`. In fact, you can run Tizen tools by full path. But I added these to system PATH environment variable:
* `<TIZEN_STUDIO_INSTALL_DIR>\tools\ide\bin`
* `<TIZEN_STUDIO_INSTALL_DIR>\tools`

Also, `sdb-run` instead of `sdb` (but maybe just `sdb` would also work), `tizen.bat` instead of `tizen`.

**Comment by Dokman** [comment] 2020-01-24 11:31
Oh okay

**Comment by Dokman** [comment] 2020-01-24 11:41
![image](https://user-images.githubusercontent.com/2290904/73066620-cd6a2400-3ea6-11ea-86e0-f0c8fe5cc180.png)

**Comment by dmitrylyzo** [comment] 2020-01-24 12:01
Oh, I didn’t look that you are using PowerShell. Then
```
$env:JELLYFIN_WEB_DIR="C:\jellyfin\jellyfin-web\dist"
npm install
```

**Comment by Dokman** [comment] 2020-01-24 12:02
![image](https://user-images.githubusercontent.com/2290904/73067738-c09aff80-3ea9-11ea-9700-bc15b8e01171.png)
it's okay?

**Comment by dmitrylyzo** [comment] 2020-01-24 12:20
> it's okay?

I also have this under Ubuntu. I am not very good in Node.js :smile: For now, I think this will not cause problems.

**Comment by Dokman** [comment] 2020-01-24 12:27
![image](https://user-images.githubusercontent.com/2290904/73069148-42d8f300-3ead-11ea-9153-c071efff48cc.png)

**Comment by dmitrylyzo** [comment] 2020-01-24 12:37
Have you turned on "Developer Mode" on your TV?

**Comment by Dokman** [comment] 2020-01-24 12:42
yes but in device manager is not working too
![image](https://user-images.githubusercontent.com/2290904/73069947-5be2a380-3eaf-11ea-944d-355463cfc24b.png)

**Comment by dmitrylyzo** [comment] 2020-01-24 13:06
It’s hard to say anything from here.
* In Developer Mode dialog, the address of the PC from which you will connect should be specified.
* After activating the Developer Mode, you must restart the TV (hold the power button for a while until the logo appears) and give SmartHub a little time (10-20 sec I think) to start.
* Device Manager can scan devices.

**Comment by Dokman** [comment] 2020-01-24 13:27
it was that my tv doesn't reboot so i had to take off the current cable

**Comment by dmitrylyzo** [comment] 2020-01-24 14:45
From your previous screen, I think there is a problem with the certificate.
![73069148-42d8f300-3ead-11ea-9153-c071efff48cc-1](https://user-images.githubusercontent.com/56478732/73076285-de2e9000-3ece-11ea-85e8-493af13ec2da.png)

https://developer.samsung.com/galaxy-watch/develop/getting-certificates/create
You must create an account on Samsung and create a Samsung certificate.
On the page with the DUIDs, you should see the DUID of your TV and the DUID of the emulator (if any).
![getting_the_certificates_09-1](https://user-images.githubusercontent.com/56478732/73076735-c0155f80-3ecf-11ea-9d2e-3f3d709bdf04.jpg)
After that rebuild WGT.
You should see something like
```
The active profile is used for signing. If you want to sign with other profile, please use '--sign' option.
Author certficate: /....../...../...../....../author.p12
Distributor1 certificate : /....../...../...../....../**distributor.p12**
```
I don’t remember whether you need to perform "Permit to install applications" from the device manager.

**Comment by Dokman** [comment] 2020-01-24 14:46
i've done that but i am having the same bug
![image](https://user-images.githubusercontent.com/2290904/73077540-a6205080-3ec0-11ea-95ad-23c073b2f640.png)

it can be that is an old model of tv?

**Comment by dmitrylyzo** [comment] 2020-01-24 15:01
Let's cheat him :smile: In fact, I tested app only in 4.0 and 5.0 (emulator). So even 3.0 is doubtful.

Try to change in `jellyfin-tizen/config.xml` line
```
    <tizen:application id="AprZAARz4r.Jellyfin" package="AprZAARz4r" required_version="3.0"/>
```
to
```
    <tizen:application id="AprZAARz4r.Jellyfin" package="AprZAARz4r" required_version="2.4"/>
```
According to [this](https://developer.samsung.com/tv/develop/specifications/tv-model-groups/) your TV has Tizen 2.4

**Comment by Dokman** [comment] 2020-01-24 15:57
it's saying the same error
![image](https://user-images.githubusercontent.com/2290904/73082965-a6bde480-3eca-11ea-8742-a6a35d41aab2.png)

**Comment by dmitrylyzo** [comment] 2020-01-24 21:07
I found TV extension 3.1.2 for Tizen Studio and got emulator 3.0.

WGT was successfully installed (but I used Tizen certificate - only for emulators). App works on Tizen 3.0.

In addition, I tried to set `required_version` to `4.0`, rebuilt WGT and installed it to `3.0` - got the same error as you. So maybe your TV has a version less than 2.4. Try to set `required_version` to `1.0`.

Also, make sure you "Permit to install applications" from the Device Manager - this installs your certificate on TV.

**Comment by Dokman** [comment] 2020-01-25 03:25
It world Wells but shows me a black screen

**Comment by dmitrylyzo** [comment] 2020-01-25 23:45
I do not found an emulator for Tizen 2.4 (if any exist). Taking into account that Tizen 3.0 has Chrome 47, Tizen 2.4 has an even older. So possibly "black screen" caused by inability to load newer syntax.

webOS 3 also has older browser (Chrome 38). Currently, it could not load Jellyfin master-branch, but PR to fix that is already submitted.

At my side, I use `const` word.

If you have time and desire to try another option, then:
1. Clone branch https://github.com/dmitrylyzo/jellyfin-web/tree/webos3_compatibility
```sh
git clone -b webos3_compatibility https://github.com/dmitrylyzo/jellyfin-web.git jellyfin-web2
```
2. Build `jellyfin-web` from `webos3_compatibility` branch. _The same way as master one_
```sh
cd jellyfin-web2
yarn install
```
3. For test I created `tizen-2` branch. Switch to it.
```sh
cd jellyfin-tizen
git fetch origin
git checkout tizen-2
```
* Prepeare `jellyfin-tizen` using "new" `jellyfin-web`.
```sh
$env:JELLYFIN_WEB_DIR="C:\jellyfin\jellyfin-web2\dist"
npm install
```
* Other stages (build-web, package, etc.) are the same.

**Comment by Dokman** [comment] 2020-01-26 09:24
I'll test It tomorrow or when i can thanks

**Comment by jkuehnemundt** [comment] 2020-01-26 17:51
It shows me a black screen too on GQ55Q8FN

**Comment by jkuehnemundt** [comment] 2020-01-26 19:03
and the emulator shows that the web page is not available.

**Comment by dmitrylyzo** [comment] 2020-01-26 19:43
@jkuehnemundt Like this?
![Screenshot_20200126_223422](https://user-images.githubusercontent.com/56478732/73140669-8e95c300-408c-11ea-87ac-d2b97dc01d2e.png)

I got this error in a situation where `www` folder is not generated (should appear in `jellyfin-tizen` folder) - stage **Prepare Interface**

I have not updated the build guide yet. It should look like this:
**Linux Shell**
```sh
JELLYFIN_WEB_DIR=../jellyfin-web/dist npm install
```
**Windows Command Line**
```sh
set JELLYFIN_WEB_DIR=C:\jellyfin\jellyfin-web\dist
npm install
```
**PowerShell**
```sh
$env:JELLYFIN_WEB_DIR="C:\jellyfin\jellyfin-web\dist"
npm install
```

After `build-web` command in `.buildResult` should be (at least):
```
www/
config.xml
icon.png
index.html
tizen.js
```

**Comment by jkuehnemundt** [comment] 2020-01-26 20:29
works like a charm 👍

**Comment by dga4130-renato** [comment] 2020-03-19 07:22
Is it not possible to get autoinstall version like emby ?

**Comment by dga4130-renato** [comment] 2020-03-24 15:47
new release for jellyfin-web fail to install... strange

**Comment by dga4130-renato** [comment] 2020-03-24 15:52
![IMG_20200324_164803](https://user-images.githubusercontent.com/43514633/77447264-c94b7b80-6def-11ea-9555-c5356120386a.jpg)

**Comment by dga4130-renato** [comment] 2020-03-27 21:15
$ yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find match for "1d12af0b04fb2337570b57d706dd97db2f904b9d" in "ref
s/heads/gh-pages,refs/heads/master,refs/tags/1.0.0,refs/tags/1.1.0,refs/tags/2.0
.0,refs/tags/2.0.1,refs/tags/2.0.2,refs/tags/2.1.0,refs/tags/2.1.1,refs/tags/2.2
.0,refs/tags/3.0.1,refs/tags/3.0.2,refs/tags/3.0.3" for "https://github.com/jell
yfin/JavascriptSubtitlesOctopus".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.

**Comment by dga4130-renato** [comment] 2020-03-27 21:41
solved with yarn cache clean

**Comment by dga4130-renato** [comment] 2020-03-27 22:08
compiled no errors, nice....
some little problem installing.. had to turn off tv a couple times but at last managed to install... nice changes, good work. thans for all support and really nice team !

**Comment by dkanada** [comment] 2020-03-29 08:12
Sounds good!

**Closed by dkanada** 2020-03-29 08:12 UTC
